### ISSUE TITLE
想问一下这样的界面能够确保开放购票的时候点击成功吗（我是第一次用大麦买票，为了看音律联觉）？

### ISSUE THREAD

**Issue by nonhana** [DracoYan-111/damai_grab_votes#31]
![Screenshot_2024-04-05-16-56-29-606_cn damai](https://github.com/DracoYan-111/damai_grab_votes/assets/105428118/d160d7a8-4e99-46a2-b1db-832324988077)
如图所示，这下面的按钮是已预约的状态，并且运行脚本，前半部分是能够跑通的，也就是不停的刷新，显示“未开放购买”
但是我不确定正式开放后，能否运行成功，希望有过抢票成功经历的人留个言！呜呜呜呜呜！！！
已预约，点进去是选票的界面：
![Screenshot_2024-04-05-17-01-32-776_cn damai](https://github.com/DracoYan-111/damai_grab_votes/assets/105428118/3ac8beaa-7160-4fc5-8365-fd2d413f1faf)

**Comment by XBWFDJ123** [comment]
哥们提醒你一句，可能会弹出滑块验证，如果出现这个基本上寄了

**Comment by nonhana** [comment]
真的假的，那咋办啊卧槽，是随机弹出的吗

**Comment by XBWFDJ123** [comment]
> 真的假的，那咋办啊卧槽，是随机弹出的吗

我也是粥p，很难讲，抢票前会显示人数过多请稍后，抢票后有概率要滑块验证后才能付款，如果你比较担心弹滑块，我建议可以试试能退款的票当作测试，

**Comment by XBWFDJ123** [comment]
> 真的假的，那咋办啊卧槽，是随机弹出的吗

建议不要完全依赖于脚本，最好机抢和手抢同时进行

**Comment by nonhana** [comment]
> > > > 真的假的，那咋办啊卧槽，是随机弹出的吗
> > > 
> > > 
> > > 建议不要完全依赖于脚本，最好机抢和手抢同时进行
> > 
> > 
> > 了解了，哎，真的难顶，你也打算抢这次的音律联觉吗
> 
> 帮别人抢，只能说祝你好运吧

感谢感谢，这次我是和朋友三个人一起抢，应该概率会大些

**Comment by Amemiya-Akira** [comment]
抢上了吗哥们儿？抢上了我第二批也试试这个，咸鱼代拍费都飙到300一张了，无论是什么档......

**Comment by nonhana** [comment]
> 抢上了吗哥们儿？抢上了我第二批也试试这个，咸鱼代拍费都飙到300一张了，无论是什么档......

我是手动抢的，这个玩意不太行啊，最后居然检测不出来购票的按钮，我建议手抢➕机抢一起但是还是手抢更加的保险😂😂😂

**Comment by Amemiya-Akira** [comment]
> > 抢上了吗哥们儿？抢上了我第二批也试试这个，咸鱼代拍费都飙到300一张了，无论是什么档......
> 
> 我是手动抢的，这个玩意不太行啊，最后居然检测不出来购票的按钮，我建议手抢➕机抢一起但是还是手抢更加的保险😂😂😂

谢谢，主要我当时看到c档还有票就犹豫了，在想抢就来不及了：（

**Comment by Amemiya-Akira** [comment]
> > 抢上了吗哥们儿？抢上了我第二批也试试这个，咸鱼代拍费都飙到300一张了，无论是什么档......
> 
> 我是手动抢的，这个玩意不太行啊，最后居然检测不出来购票的按钮，我建议手抢➕机抢一起但是还是手抢更加的保险😂😂😂

本来也就想着买个e或者d

**Comment by nonhana** [comment]
> > > 抢上了吗哥们儿？抢上了我第二批也试试这个，咸鱼代拍费都飙到300一张了，无论是什么档......
> > 
> > 
> > 我是手动抢的，这个玩意不太行啊，最后居然检测不出来购票的按钮，我建议手抢➕机抢一起但是还是手抢更加的保险😂😂😂
> 
> 谢谢，主要我当时看到c档还有票就犹豫了，在想抢就来不及了：（

我抢到了5.5 18:30的票，三张连坐，还是比较开心的

**Comment by pareshgami** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
tzashton, @Bkyk, @sjx8999, @JupiterXiaoxiaoYu, @shuyabin, @0x4E33, @hi-chenerge, @summer1998x, @valueflowever, @windgentle, @matengteng, @kitscode, @zhuimengsa, @LxzLLL, @dpwupan, @whitespur, @KevinMyDing, @0xabz, @Ha2ryZhang, @coldstar1993, @wkshare, @FreedomKey89, @Jolly23, @Nomiracle, @madao708, @jenkzhang, @MrGr00t, @mrwenhui, @zxingstar, @yuliyu123, @Lumend, @kosmosr, @terrorgeek, @havingautism, @wangyangv1, @scluojie, @recursion128, @0lh, @iHaveFiveDogs, @cccchuck, @lghthon, @Tian2000, @johnden, @cielu, @x7c7v7i87, @dbhop, @ericyue, @yeecai, @zsp00, @Anomours
